name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  call-publish:
    uses: Corsinvest/.github/.github/workflows/cv4pve-cli-publish.yml@main
    secrets:
      WINGET_TOKEN: ${{ secrets.WINGET_TOKEN }}
    with:
      project-name: cv4pve-vdi
      project-path: src/Corsinvest.ProxmoxVE.Vdi/Corsinvest.ProxmoxVE.Vdi.csproj
      winget-id: Corsinvest.cv4pve.vdi